version: 0.2

# Variables de entorno que deben ser configuradas en el proyecto CodeBuild en la consola de AWS
# AWS_ACCOUNT_ID: Tu ID de cuenta de AWS (ej: 534224643194)
# AWS_DEFAULT_REGION: us-east-2
# IMAGE_REPO_NAME: api-monedas (nombre de tu repositorio ECR)
# CONTAINER_NAME: api-monedas-container (nombre del contenedor en tu task-definition.json)

phases:

  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo pre_build...

  build:
    commands:
      - echo creando cloudformation stack...
      - ./scripts/deploy.sh udeabootcamp-stack templates/vpc.yml
      - echo stack creado

  post_build:
    commands:
      - echo post_build...