version: 0.2

env:
  variables:
    STACK_NAME: "udeabootcamp-stack"
    TEMPLATE_FILE: "templates/main.yml"
    REGION: "us-east-2"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando AWS CLI..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Validando que el archivo de plantilla exista..."

  build:
    commands:
      - echo "Desplegando stack de CloudFormation..."
      - aws cloudformation deploy --stack-name "$STACK_NAME" --template-file "$TEMPLATE_FILE" --capabilities CAPABILITY_NAMED_IAM --region "$REGION"

  post_build:
    commands:
      - echo "Despliegue completado exitosamente."
      - aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION"

artifacts:
  files:
    - '**/*'