version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo pre_build...

  build:
    commands:
      - echo creando cloudformation stack...
      - aws cloudformation deploy --stack-name "$STACK_NAME" --template-file "$TEMPLATE_FILE" --capabilities CAPABILITY_NAMED_IAM --region "$REGION"
      - echo stack creado

  post_build:
    commands:
      - echo post_build...