version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo pre_build...

  build:
    commands:
      - echo creando cloudformation stack...
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh udeabootcamp-stack templates/vpc.yml
      - echo stack creado

  post_build:
    commands:
      - echo post_build...