version: 0.2

env:
  variables:
    REGION: "us-east-2" # Región por defecto, se puede sobrescribir en la consola de CodeBuild

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo "Fase pre_build..."

  build:
    commands:
      - echo "Creando CloudFormation stack..."
      # Validar variables
      - |
        if [ -z "udeabootcamp-stack" ] || [ -z "templates/vpc.yml" ]; then
          echo "Error: Falta el nombre del stack o el archivo de template."
          exit 1
        fi
      # Ejecutar despliegue
      - aws cloudformation deploy \
          --stack-name "udeabootcamp-stack" \
          --template-file "templates/vpc.yml" \
          --capabilities CAPABILITY_NAMED_IAM \
          --region "$REGION"
      - echo "Stack creado correctamente."

  post_build:
    commands:
      - echo "Fase post_build..."