AWSTemplateFormatVersion: 2010-09-09
Description: >
  CloudFormation - VPC y Subred privada para el proyecto UdeABootCamp

Resources:
  # VPC
  UdeABootCampVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: UdeABootCamp-VPC

  # Subnet privada
  UdeABootCampPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref UdeABootCampVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: UdeABootCamp-Private-Subnet-1

  # Security Group base (para usar luego con ECS/RDS)
  UdeABootCampBaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG base para UdeABootCamp
      VpcId: !Ref UdeABootCampVPC
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: UdeABootCamp-BaseSG

Outputs:
  VPCId:
    Description: ID de la VPC de UdeABootCamp
    Value: !Ref UdeABootCampVPC
    Export:
      Name: UdeABootCamp-VPCId

  PrivateSubnet1Id:
    Description: ID de la subred privada
    Value: !Ref UdeABootCampPrivateSubnet1
    Export:
      Name: UdeABootCamp-PrivateSubnet1Id

  BaseSecurityGroupId:
    Description: ID del Security Group base
    Value: !Ref UdeABootCampBaseSG
    Export:
      Name: UdeABootCamp-BaseSGId